import test from 'node:test';
import assert from 'node:assert/strict';
import {birthScale,mergeEchoPose} from '../dist/effects.js';
import {mergeScore,createRoundInheritance} from '../dist/round-rules.js';
test('elastic birth keyframes and final settle',()=>{for(const [t,s] of [[-1,0],[0,.55],[95,1.18],[165,.94],[225,1.04],[280,1],[500,1]])assert.equal(birthScale(t),s);assert.ok(birthScale(50)>.55&&birthScale(50)<1.18);});
test('absorption follows compression, not the collider',()=>{assert.equal(mergeEchoPose(0).scale,1);assert.equal(mergeEchoPose(80).scale,.92);assert.equal(mergeEchoPose(80).progress,0);assert.equal(mergeEchoPose(170).progress,1);assert.equal(mergeEchoPose(170).alpha,0);});
test('reduced motion is restrained and ends cleanly',()=>{assert.equal(birthScale(100,true),1);assert.equal(mergeEchoPose(60,true).alpha,0);assert.equal(mergeEchoPose(50,true).progress,0);});
test('score uses rounded current multiplier',()=>{assert.equal(mergeScore(2,1.25),25);assert.equal(mergeScore(3,1.5),60);});
test('round gift is consumed once across restarts',()=>{const data={};const r=createRoundInheritance({readStorage:(k,v)=>data[k]??v,writeStorage:(k,v)=>data[k]=v});r.startRound();r.recordMerge(9);r.settle();r.settle();assert.deepEqual(r.startRound(),{level:8,score:128000});assert.equal(r.startRound(),null);});
import {createCollection} from '../dist/collection.js';
import {createPetManager} from '../dist/pet-manager.js';
function petFixture(random=()=>.4){const data={},stages=Array.from({length:11},(_,i)=>({level:i+1}));const storage={readStorage:(k,v)=>data[k]??v,writeStorage:(k,v)=>data[k]=v};const collection=createCollection({stages,...storage});const calls=[];const view={show:(...args)=>calls.push(args),select(){},pause(){},look(){},cancel(){}};const pet=createPetManager({collection,...storage,view,random});return {pet,collection,data,calls,storage,stages};}
test('one validated collection migrates old highest and rejects locked pets',()=>{const f=petFixture();assert.equal(f.pet.select(2),false);f.collection.unlock(2);assert.equal(f.pet.select(2),true);assert.equal(f.data.pet.selectedId,2);f.pet.reload();assert.equal(f.pet.selectedId,2);f.data.pet={selectedId:99};f.pet.reload();assert.equal(f.pet.selectedId,1);delete f.data.collection;delete f.data.pet;f.data.rounds=[{highest:6},{highest:999}];f.pet.reload();assert.deepEqual(f.collection.ids(),[1,2,3,4,5,6]);delete f.data.rounds;f.pet.reload();assert.deepEqual(f.collection.ids(),[1]);});
test('pet merge cooldown, combo bands and self cameo are bounded',()=>{const {pet,collection}=petFixture();pet.react('MERGE',{level:2});const count=pet.snapshot().reactions;for(let i=0;i<100;i++)pet.react('MERGE',{level:2});assert.equal(pet.snapshot().reactions,count);pet.react('COMBO',{chain:8});assert.equal(pet.snapshot().state,'EXCITED');const n=pet.snapshot().reactions;for(let i=8;i<100;i++)pet.react('COMBO',{chain:i});assert.equal(pet.snapshot().reactions,n);collection.unlock(2);pet.select(2);pet.react('MERGE',{level:2});assert.equal(pet.snapshot().variant,'self');pet.update(1000);pet.react('MERGE',{level:2});assert.notEqual(pet.snapshot().variant,'self');});
test('danger, records, gameover, pause, restart and sleep lifecycle',()=>{const {pet}=petFixture(()=>.2);pet.react('NEAR_GAME_OVER',{active:true});pet.update(1000);assert.equal(pet.snapshot().state,'SCARED');pet.react('NEAR_GAME_OVER',{active:false});assert.equal(pet.snapshot().state,'IDLE');pet.react('NEW_HIGH_SCORE');assert.equal(pet.snapshot().variant,'record');pet.setPaused(true);pet.update(9000);assert.equal(pet.snapshot().state,'EXCITED');pet.setPaused(false);pet.react('GAME_OVER');pet.update(3000);assert.equal(pet.snapshot().state,'IDLE');assert.equal(pet.snapshot().ended,true);pet.reset();assert.equal(pet.snapshot().ended,false);pet.update(30000);assert.equal(pet.snapshot().state,'SLEEPING');pet.react('DROP');assert.equal(pet.snapshot().state,'LOOKING');});
test('twenty rapid clicks dodge once and petting recovers cleanly',()=>{const {pet}=petFixture();for(let i=0;i<20;i++)pet.click();assert.equal(pet.snapshot().clickCount,20);assert.equal(pet.snapshot().variant,'dodge');assert.ok(pet.snapshot().reactions<=3);pet.update(2500);assert.equal(pet.snapshot().state,'IDLE');assert.equal(pet.pet(),true);assert.equal(pet.pet(),false);pet.update(1200);assert.equal(pet.snapshot().state,'IDLE');});
